language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

branches:
  only:
  - test

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test DockerDemoTests/DockerDemoTests.csproj

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master # Commit to master instead of gh-pages
  github_token: $GH_TOKEN
  keep_history: true # By default, Travis uses push --force and wipes out commit history
  verbose: true
  on:
    branches:    
      only:      
        - test

global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
 - DOTNET_CLI_TELEMETRY_OPTOUT=1